os:
    - linux
    - osx
sudo: required
dist: trusty
osx_image: xcode7.2

language: rust

addons:
  apt:
    packages:
    - pkg-config

install: eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script: ./travis-test-all.sh
