os:
    - linux
    - osx
sudo: required
dist: trusty
osx_image: xcode9.1

language: rust

addons:
  apt:
    packages:
    - pkg-config

install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
  - swiftenv install 4.0.2
script:
  - ./travis-test-all.sh
